from typing import Any, Dict, List, Optional
from typing_extensions import TypedDict


class IncidentState(TypedDict, total=False):
    """Shared state for the incident triage graph."""

    incident: Dict[str, Any]
    normalized_incident: Dict[str, Any]

    # Proposals generated by the SRE reviewer node
    proposals: List[Dict[str, Any]]

    # Judgment from the judge node
    judgment: Dict[str, Any]

    # Human review result (approval, rejection, comments)
    human_decision: Dict[str, Any]

    # Actions executed by the MCP node
    actions: List[Dict[str, Any]]

    # Control / routing fields
    next_node: Optional[str]
    done: bool
